version: "3"

services: 
    rabbitmq:
        image: rabbitmq:3.8-management
        container_name: rabbitmq
        hostname: "rabbITMQ-machine"
        env_file: prototype.env
        networks:
            - "iotstack"
        ports: 
            - "1883:1883" # MQTT Port
            - "5672:5672" # AMQP Port
            - "15672:15672" # Management UI HTTP
        volumes: 
            - ./rabbitmq/plugins/enabled_plugins:/etc/rabbitmq/enabled_plugins
            - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
            - rabbitmq_data:/var/lib/rabbitmq
        
    influxdb:
        image: influxdb:2.0.4
        container_name: influxdb
        env_file: prototype.env
        networks: 
            - "iotstack"
        ports:
            - "8086:8086"
        volumes: 
            - influxdb_data:/root/.influxdbv2
    
    telegraf:
        image: telegraf:1.18
        container_name: telegraf
        env_file: prototype.env
        restart: on-failure # required till user credentials created
        links: 
            - influxdb
            - rabbitmq
        depends_on: 
            # do not start before RabbitMQ, InfluxDB
            - rabbitmq
            - influxdb
        networks: 
            - "iotstack"
        volumes: 
            - ./telegraf/telegraf.toml:/etc/telegraf/telegraf.conf:ro

volumes: 
    rabbitmq_data:
    influxdb_data:

networks:
    iotstack:
        external: true